### ISSUE TITLE
Not all zip codes are listed - only "zip code tablulated areas" (ZCTA's)

### ISSUE THREAD

**Issue by LukeSwart** [jgoodall/us-maps#2]
It appears that some zip codes are missing. For example, in the "zip code to FIPS file" here: https://raw.githubusercontent.com/jgoodall/us-maps/master/reference/zip-codes.json, I am unable to find these zip codes:

36130
40621
04333

There are many more zip codes that are not included either. This leads me to believe that the file is actually a mapping of "zip code tabulated areas" (ZCTA's), not zip codes. Therefore, I think it would be reasonable to include a mapping of zip codes to ZCTA's. Here is a source that can map ZCTA's to their corresponding zip codes:

http://udsmapper.org/zcta-crosswalk.cfm

Maybe we should include that mapping file in this repo as well?

**Comment by jgoodall** [comment]
@LukeSwart - you are correct, these were ZCTAs (implied in the zip code section, though not explicit). If you would like to add a ZCTA mapping to zip codes using the crosswalk file, that would be great. Please issue a pull request and I will merge.

**Comment by loganpowell** [comment]
Just a note, not all zipcodes are represented by ZCTAs
